steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd src && docker build -t gcr.io/$PROJECT_ID/docker-nginx-certbox . && docker push gcr.io/$PROJECT_ID/docker-nginx-certbox
